# Generated by Django 5.2.14 on 2026-06-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('mode', models.TextField()),
                ('match_id', models.PositiveBigIntegerField()),
                ('stage_id', models.PositiveBigIntegerField()),
                ('turn_number', models.PositiveIntegerField()),
                ('action_code', models.TextField(choices=[('curse', 'curse'), ('guard', 'guard'), ('insight', 'insight'), ('trick', 'trick'), ('silence', 'silence'), ('contract', 'contract'), ('seal', 'seal')])),
                ('info_target_key', models.TextField(blank=True, null=True)),
                ('decision_duration_ms', models.PositiveIntegerField()),
                ('sanity_before', models.PositiveIntegerField()),
                ('ritual_power_before', models.PositiveIntegerField()),
                ('curse_marks_before', models.PositiveIntegerField()),
                ('opponent_action_code', models.TextField(choices=[('curse', 'curse'), ('guard', 'guard'), ('insight', 'insight'), ('trick', 'trick'), ('silence', 'silence'), ('contract', 'contract'), ('seal', 'seal')])),
                ('result_code', models.TextField()),
                ('acquired_clue_id', models.TextField(blank=True, null=True)),
                ('clue_truth_state', models.TextField(blank=True, null=True)),
                ('match_outcome', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('aggression', models.FloatField()),
                ('defense', models.FloatField()),
                ('insight_focus', models.FloatField()),
                ('deception', models.FloatField()),
                ('risk_preference', models.FloatField()),
                ('silence_reliance', models.FloatField()),
                ('crisis_guard_rate', models.FloatField()),
                ('crisis_contract_rate', models.FloatField()),
                ('late_choice_rate', models.FloatField()),
            ],
        ),
    ]
