# Generated by Django 5.2.14 on 2026-06-04 01:16

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='RetrievalChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.TextField()),
                ('chunk_id', models.TextField()),
                ('source_path', models.TextField()),
                ('schema_version', models.TextField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField()),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.TextField()),
                ('source_path', models.TextField()),
                ('schema_version', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('caller', models.TextField()),
                ('document_id', models.TextField()),
                ('chunk_id', models.TextField()),
                ('score', models.FloatField()),
                ('threshold', models.FloatField()),
                ('top_k', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
