# Generated by Django 5.2.14 on 2026-06-04 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField()),
                ('ai_story_matches', models.PositiveIntegerField()),
                ('ai_story_wins', models.PositiveIntegerField()),
                ('ai_story_losses', models.PositiveIntegerField()),
                ('style_label', models.TextField(blank=True, null=True)),
                ('style_display_text', models.TextField(blank=True, null=True)),
                ('style_summary_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
