# Generated by Django 5.2.14 on 2026-06-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.TextField(choices=[('ai_story', 'ai_story')])),
                ('status', models.TextField(choices=[('active', 'active'), ('resolved', 'resolved'), ('abandoned', 'abandoned')])),
                ('winner_participant_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveBigIntegerField()),
                ('participant_type', models.TextField(choices=[('human', 'human'), ('apparition', 'apparition')])),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('apparition_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('side', models.TextField()),
                ('sanity', models.PositiveIntegerField()),
                ('ritual_power', models.PositiveIntegerField()),
                ('curse_marks', models.PositiveIntegerField()),
                ('secret_exposure', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'match_participants',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveBigIntegerField()),
                ('turn_number', models.PositiveIntegerField()),
                ('status', models.TextField(choices=[('awaiting_player', 'awaiting_player'), ('submitted', 'submitted'), ('resolved', 'resolved'), ('timed_out', 'timed_out')])),
                ('deadline_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turns',
            },
        ),
        migrations.CreateModel(
            name='TurnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_id', models.PositiveBigIntegerField()),
                ('result_json', models.JSONField()),
                ('public_log_json', models.JSONField()),
                ('private_log_json', models.JSONField()),
                ('schema_version', models.TextField()),
            ],
            options={
                'db_table': 'turn_results',
            },
        ),
        migrations.CreateModel(
            name='ActionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_id', models.PositiveBigIntegerField()),
                ('participant_id', models.PositiveBigIntegerField()),
                ('action_code', models.TextField(choices=[('curse', 'curse'), ('guard', 'guard'), ('insight', 'insight'), ('trick', 'trick'), ('silence', 'silence'), ('contract', 'contract'), ('seal', 'seal')])),
                ('info_target_key', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('client_nonce', models.UUIDField()),
            ],
            options={
                'db_table': 'action_submissions',
                'constraints': [models.UniqueConstraint(fields=('turn_id', 'participant_id', 'client_nonce'), name='action_submission_turn_participant_client_nonce_unique')],
            },
        ),
    ]
