# Generated by Django 5.2.14 on 2026-06-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('taboo', models.TextField()),
                ('base_policy_json', models.JSONField()),
            ],
            options={
                'db_table': 'apparitions',
            },
        ),
        migrations.CreateModel(
            name='FalseClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparition_id', models.PositiveBigIntegerField()),
                ('content', models.TextField()),
                ('trigger_condition_json', models.JSONField()),
            ],
            options={
                'db_table': 'false_clues',
            },
        ),
        migrations.CreateModel(
            name='PlayerStoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('stage_id', models.PositiveBigIntegerField()),
                ('status', models.TextField()),
                ('attempts', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_story_progress',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.PositiveBigIntegerField()),
                ('apparition_id', models.PositiveBigIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('victory_condition_json', models.JSONField()),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='StoryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('difficulty', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'story_cases',
            },
        ),
        migrations.CreateModel(
            name='TrueNameFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparition_id', models.PositiveBigIntegerField()),
                ('label', models.TextField()),
                ('content', models.TextField()),
                ('reveal_condition_json', models.JSONField()),
            ],
            options={
                'db_table': 'true_name_fragments',
            },
        ),
    ]
