# Generated by Django 5.2.14 on 2026-06-04 01:16

import backend.apps.accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('jti', models.UUIDField(unique=True)),
                ('family_id', models.UUIDField()),
                ('token_hash', models.TextField()),
                ('status', models.TextField(choices=[('active', 'active'), ('rotated', 'rotated'), ('revoked', 'revoked'), ('reused', 'reused')])),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reused_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by_jti', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(choices=[('refresh token reuse 감지', 'refresh token reuse 감지'), ('refresh token family revoke', 'refresh token family revoke'), ('CSRF 실패', 'CSRF 실패'), ('로그인 실패 반복', '로그인 실패 반복'), ('권한 없는 match 접근 시도', '권한 없는 match 접근 시도'), ('participant가 아닌 사용자의 행동 제출 시도', 'participant가 아닌 사용자의 행동 제출 시도')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', backend.apps.accounts.managers.UserManager()),
            ],
        ),
    ]
