# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="request_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="user_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
