# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_securityevent_metadata_request_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginFailureThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("first_failed_at", models.DateTimeField()),
                ("last_failed_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "ip_address"],
                        name="acct_login_fail_ident_idx",
                    ),
                    models.Index(
                        fields=["blocked_until"],
                        name="acct_login_fail_block_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "ip_address"),
                        name="accounts_login_failure_email_ip_unique",
                    )
                ],
            },
        ),
    ]
