# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_loginfailurethrottle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveBigIntegerField()),
                ("token_hash", models.TextField(unique=True)),
                ("requested_email", models.EmailField(max_length=254)),
                ("request_ip", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token_hash"], name="acct_pwd_reset_hash_idx"),
                    models.Index(fields=["expires_at"], name="acct_pwd_reset_exp_idx"),
                    models.Index(fields=["user_id"], name="acct_pwd_reset_user_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("first_requested_at", models.DateTimeField()),
                ("last_requested_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email", "ip_address"], name="acct_pwd_reset_ident_idx"),
                    models.Index(fields=["blocked_until"], name="acct_pwd_reset_block_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "ip_address"),
                        name="accounts_password_reset_email_ip_unique",
                    )
                ],
            },
        ),
    ]
