# Generated by Django 5.2.14 on 2026-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.TextField(choices=[('refresh token reuse 감지', 'refresh token reuse 감지'), ('refresh token family revoke', 'refresh token family revoke'), ('CSRF 실패', 'CSRF 실패'), ('로그인 실패 반복', '로그인 실패 반복'), ('권한 없는 match 접근 시도', '권한 없는 match 접근 시도'), ('participant가 아닌 사용자의 행동 제출 시도', 'participant가 아닌 사용자의 행동 제출 시도'), ('password reset requested', 'password reset requested'), ('password reset delivery unavailable', 'password reset delivery unavailable'), ('password reset succeeded', 'password reset succeeded'), ('password reset token expired', 'password reset token expired'), ('password reset token reused', 'password reset token reused'), ('password reset token invalid', 'password reset token invalid')]),
        ),
    ]
